-- Live hardening for agency usage:
-- 1) tenant-safe audits access
-- 2) stricter cost log visibility
-- 3) centralized edge-function rate limiting

-- ---------------------------------------------------------------------------
-- Audits: scope rows to creator (or management role) instead of all auth users.
-- ---------------------------------------------------------------------------
alter table public.audits
  add column if not exists created_by uuid references auth.users(id);
create index if not exists audits_created_by_domain_created_at_idx
  on public.audits (created_by, domain, created_at desc);
drop policy if exists "authenticated_read_audits" on public.audits;
drop policy if exists "users_read_own_audits" on public.audits;
drop policy if exists "users_insert_own_audits" on public.audits;
create policy "users_read_own_audits"
  on public.audits
  for select
  to authenticated
  using (
    created_by = auth.uid()
    or coalesce(public.has_role(auth.uid(), 'management'::public.app_role), false)
  );
create policy "users_insert_own_audits"
  on public.audits
  for insert
  to authenticated
  with check (
    created_by = auth.uid()
    or coalesce(public.has_role(auth.uid(), 'management'::public.app_role), false)
  );
-- ---------------------------------------------------------------------------
-- Cost logs: prevent cross-user reads for generic (client_id is null) entries.
-- ---------------------------------------------------------------------------
update public.cost_logs cl
set created_by = c.created_by
from public.clients c
where cl.created_by is null
  and cl.client_id = c.id;
drop policy if exists "Users can read cost logs" on public.cost_logs;
drop policy if exists "Users can insert cost logs" on public.cost_logs;
drop policy if exists "Users can update cost logs" on public.cost_logs;
drop policy if exists "Users can delete cost logs" on public.cost_logs;
create policy "Users can read cost logs"
  on public.cost_logs
  for select
  using (
    created_by = auth.uid()
    or (
      client_id is not null
      and public.can_access_client(client_id)
    )
    or coalesce(public.has_role(auth.uid(), 'management'::public.app_role), false)
  );
create policy "Users can insert cost logs"
  on public.cost_logs
  for insert
  with check (
    auth.uid() is not null
    and created_by = auth.uid()
    and (
      client_id is null
      or public.can_access_client(client_id)
    )
  );
create policy "Users can update cost logs"
  on public.cost_logs
  for update
  using (
    created_by = auth.uid()
    or coalesce(public.has_role(auth.uid(), 'management'::public.app_role), false)
  )
  with check (
    created_by = auth.uid()
    or coalesce(public.has_role(auth.uid(), 'management'::public.app_role), false)
  );
create policy "Users can delete cost logs"
  on public.cost_logs
  for delete
  using (
    created_by = auth.uid()
    or coalesce(public.has_role(auth.uid(), 'management'::public.app_role), false)
  );
-- ---------------------------------------------------------------------------
-- Rate limiting table + RPC for edge functions (service-role only).
-- ---------------------------------------------------------------------------
create table if not exists public.function_rate_limits (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  function_name text not null,
  action_name text not null,
  window_start timestamptz not null,
  request_count integer not null default 1 check (request_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists function_rate_limits_unique_window_idx
  on public.function_rate_limits (user_id, function_name, action_name, window_start);
create index if not exists function_rate_limits_updated_at_idx
  on public.function_rate_limits (updated_at desc);
alter table public.function_rate_limits enable row level security;
drop policy if exists "service_role_manage_function_rate_limits" on public.function_rate_limits;
create policy "service_role_manage_function_rate_limits"
  on public.function_rate_limits
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');
revoke all on table public.function_rate_limits from anon;
revoke all on table public.function_rate_limits from authenticated;
grant select, insert, update, delete on table public.function_rate_limits to service_role;
create or replace function public.consume_rate_limit(
  p_user_id uuid,
  p_function_name text,
  p_action_name text,
  p_window_seconds integer,
  p_max_requests integer
)
returns table(
  allowed boolean,
  request_count integer,
  reset_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_now timestamptz := now();
  v_window_seconds integer := greatest(coalesce(p_window_seconds, 60), 1);
  v_max_requests integer := greatest(coalesce(p_max_requests, 1), 1);
  v_window_start timestamptz;
  v_request_count integer;
begin
  v_window_start := to_timestamp(
    floor(extract(epoch from v_now) / v_window_seconds) * v_window_seconds
  );

  insert into public.function_rate_limits (
    user_id,
    function_name,
    action_name,
    window_start,
    request_count,
    updated_at
  )
  values (
    p_user_id,
    p_function_name,
    p_action_name,
    v_window_start,
    1,
    v_now
  )
  on conflict (user_id, function_name, action_name, window_start)
  do update
    set request_count = public.function_rate_limits.request_count + 1,
        updated_at = excluded.updated_at
  returning public.function_rate_limits.request_count into v_request_count;

  allowed := v_request_count <= v_max_requests;
  request_count := v_request_count;
  reset_at := v_window_start + make_interval(secs => v_window_seconds);

  return next;
end;
$$;
revoke all on function public.consume_rate_limit(uuid, text, text, integer, integer) from public;
grant execute on function public.consume_rate_limit(uuid, text, text, integer, integer) to service_role;
