create table if not exists public.audits (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  domain text not null,
  country text not null,
  language text not null,
  competitors text[] not null default '{}',
  provider text not null default 'dataforseo',
  status text not null default 'completed',
  normalized jsonb not null default '{}'::jsonb,
  endpoint_status jsonb not null default '[]'::jsonb,
  raw jsonb not null default '{}'::jsonb,
  warnings text[] not null default '{}'
);
create index if not exists audits_domain_created_at_idx
  on public.audits (domain, created_at desc);
alter table public.audits enable row level security;
drop policy if exists "service_role_full_access_audits" on public.audits;
create policy "service_role_full_access_audits"
  on public.audits
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');
drop policy if exists "authenticated_read_audits" on public.audits;
create policy "authenticated_read_audits"
  on public.audits
  for select
  using (auth.role() = 'authenticated');
